//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.ImportDemo.Core.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.ImportDemo.Core.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Good.
        /// </summary>
        internal static string Enum_DegreeClassification_AverageGood {
            get {
                return ResourceManager.GetString("Enum_DegreeClassification_AverageGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent.
        /// </summary>
        internal static string Enum_DegreeClassification_Excellent {
            get {
                return ResourceManager.GetString("Enum_DegreeClassification_Excellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        internal static string Enum_DegreeClassification_Good {
            get {
                return ResourceManager.GetString("Enum_DegreeClassification_Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinary.
        /// </summary>
        internal static string Enum_DegreeClassification_Ordinary {
            get {
                return ResourceManager.GetString("Enum_DegreeClassification_Ordinary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Good.
        /// </summary>
        internal static string Enum_DegreeClassification_VeryGood {
            get {
                return ResourceManager.GetString("Enum_DegreeClassification_VeryGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructed.
        /// </summary>
        internal static string Enum_ExerciseType_Constructed {
            get {
                return ResourceManager.GetString("Enum_ExerciseType_Constructed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        internal static string Enum_ExerciseType_Selected {
            get {
                return ResourceManager.GetString("Enum_ExerciseType_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Enum_Gender_Female {
            get {
                return ResourceManager.GetString("Enum_Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Enum_Gender_Male {
            get {
                return ResourceManager.GetString("Enum_Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Enum_Gender_Other {
            get {
                return ResourceManager.GetString("Enum_Gender_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Divorced.
        /// </summary>
        internal static string Enum_MaritalStatus_Divorced {
            get {
                return ResourceManager.GetString("Enum_MaritalStatus_Divorced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engaged.
        /// </summary>
        internal static string Enum_MaritalStatus_Engaged {
            get {
                return ResourceManager.GetString("Enum_MaritalStatus_Engaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Married.
        /// </summary>
        internal static string Enum_MaritalStatus_Married {
            get {
                return ResourceManager.GetString("Enum_MaritalStatus_Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separated.
        /// </summary>
        internal static string Enum_MaritalStatus_Separated {
            get {
                return ResourceManager.GetString("Enum_MaritalStatus_Separated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        internal static string Enum_MaritalStatus_Single {
            get {
                return ResourceManager.GetString("Enum_MaritalStatus_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widow.
        /// </summary>
        internal static string Enum_MaritalStatus_Widow {
            get {
                return ResourceManager.GetString("Enum_MaritalStatus_Widow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widower.
        /// </summary>
        internal static string Enum_MaritalStatus_Widower {
            get {
                return ResourceManager.GetString("Enum_MaritalStatus_Widower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructed.
        /// </summary>
        internal static string Enum_QuestionType_Constructed {
            get {
                return ResourceManager.GetString("Enum_QuestionType_Constructed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi selected.
        /// </summary>
        internal static string Enum_QuestionType_MultiSelected {
            get {
                return ResourceManager.GetString("Enum_QuestionType_MultiSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One selected.
        /// </summary>
        internal static string Enum_QuestionType_OneSelected {
            get {
                return ResourceManager.GetString("Enum_QuestionType_OneSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discuss.
        /// </summary>
        internal static string Enum_ThreadType_Discuss {
            get {
                return ResourceManager.GetString("Enum_ThreadType_Discuss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string Enum_ThreadType_Notice {
            get {
                return ResourceManager.GetString("Enum_ThreadType_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Enum_ThreadType_Other {
            get {
                return ResourceManager.GetString("Enum_ThreadType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question/Help.
        /// </summary>
        internal static string Enum_ThreadType_Question {
            get {
                return ResourceManager.GetString("Enum_ThreadType_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared.
        /// </summary>
        internal static string Enum_ThreadType_Shared {
            get {
                return ResourceManager.GetString("Enum_ThreadType_Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bachelor.
        /// </summary>
        internal static string Enum_TrainningLevel_Bachelor {
            get {
                return ResourceManager.GetString("Enum_TrainningLevel_Bachelor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diploma.
        /// </summary>
        internal static string Enum_TrainningLevel_Diploma {
            get {
                return ResourceManager.GetString("Enum_TrainningLevel_Diploma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate Professional Education.
        /// </summary>
        internal static string Enum_TrainningLevel_IntermediateProfessionalEducation {
            get {
                return ResourceManager.GetString("Enum_TrainningLevel_IntermediateProfessionalEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        internal static string Enum_TrainningLevel_Master {
            get {
                return ResourceManager.GetString("Enum_TrainningLevel_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philosophy Doctor.
        /// </summary>
        internal static string Enum_TrainningLevel_PhilosophyDoctor {
            get {
                return ResourceManager.GetString("Enum_TrainningLevel_PhilosophyDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Enum_VideoType_Upload {
            get {
                return ResourceManager.GetString("Enum_VideoType_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url Custom.
        /// </summary>
        internal static string Enum_VideoType_UrlCustom {
            get {
                return ResourceManager.GetString("Enum_VideoType_UrlCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube Id.
        /// </summary>
        internal static string Enum_VideoType_YoutubeId {
            get {
                return ResourceManager.GetString("Enum_VideoType_YoutubeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probationary.
        /// </summary>
        internal static string Enum_WorkStatus_Probationary {
            get {
                return ResourceManager.GetString("Enum_WorkStatus_Probationary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Work.
        /// </summary>
        internal static string Enum_WorkStatus_QuitWork {
            get {
                return ResourceManager.GetString("Enum_WorkStatus_QuitWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retired.
        /// </summary>
        internal static string Enum_WorkStatus_Retired {
            get {
                return ResourceManager.GetString("Enum_WorkStatus_Retired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainning.
        /// </summary>
        internal static string Enum_WorkStatus_Trainning {
            get {
                return ResourceManager.GetString("Enum_WorkStatus_Trainning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working.
        /// </summary>
        internal static string Enum_WorkStatus_Working {
            get {
                return ResourceManager.GetString("Enum_WorkStatus_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact MISA to help!.
        /// </summary>
        internal static string Exception_Message_General {
            get {
                return ResourceManager.GetString("Exception_Message_General", resourceCulture);
            }
        }
    }
}
