//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.ImportDemo.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.ImportDemo.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày/Tháng/Năm.
        /// </summary>
        public static string Enum_DateDisplaySetting_ddmmyyyy {
            get {
                return ResourceManager.GetString("Enum_DateDisplaySetting_ddmmyyyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng/ Năm.
        /// </summary>
        public static string Enum_DateDisplaySetting_mmyyyy {
            get {
                return ResourceManager.GetString("Enum_DateDisplaySetting_mmyyyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        public static string Enum_DateDisplaySetting_yyyy {
            get {
                return ResourceManager.GetString("Enum_DateDisplaySetting_yyyy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nữ.
        /// </summary>
        public static string Enum_Gender_Female {
            get {
                return ResourceManager.GetString("Enum_Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nam.
        /// </summary>
        public static string Enum_Gender_Male {
            get {
                return ResourceManager.GetString("Enum_Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        public static string Enum_Gender_Other {
            get {
                return ResourceManager.GetString("Enum_Gender_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tham gia.
        /// </summary>
        public static string Enum_InsurranceStatus_NotParticipating {
            get {
                return ResourceManager.GetString("Enum_InsurranceStatus_NotParticipating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tham gia.
        /// </summary>
        public static string Enum_InsurranceStatus_Participating {
            get {
                return ResourceManager.GetString("Enum_InsurranceStatus_Participating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K1.
        /// </summary>
        public static string Enum_ResidentialAreaType_K1 {
            get {
                return ResourceManager.GetString("Enum_ResidentialAreaType_K1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K2.
        /// </summary>
        public static string Enum_ResidentialAreaType_K2 {
            get {
                return ResourceManager.GetString("Enum_ResidentialAreaType_K2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K3.
        /// </summary>
        public static string Enum_ResidentialAreaType_K3 {
            get {
                return ResourceManager.GetString("Enum_ResidentialAreaType_K3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        public static string Enum_YesNoOption_False {
            get {
                return ResourceManager.GetString("Enum_YesNoOption_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có.
        /// </summary>
        public static string Enum_YesNoOption_True {
            get {
                return ResourceManager.GetString("Enum_YesNoOption_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn không có quyền truy cập tài nguyên này..
        /// </summary>
        public static string Erro_NotAuthentication {
            get {
                return ResourceManager.GetString("Erro_NotAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp xuất khẩu lỗi..
        /// </summary>
        public static string Error_ExportFileFormat {
            get {
                return ResourceManager.GetString("Error_ExportFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File không đúng định dạng. Vui lòng kiểm tra lại..
        /// </summary>
        public static string Error_FileFormat {
            get {
                return ResourceManager.GetString("Error_FileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin lao động {0} đã có trên hệ thống.
        /// </summary>
        public static string Error_ImportDataDuplicateInDatabase {
            get {
                return ResourceManager.GetString("Error_ImportDataDuplicateInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin lao động {0} bị trùng trong File Excel.
        /// </summary>
        public static string Error_ImportDataDuplicateInFile {
            get {
                return ResourceManager.GetString("Error_ImportDataDuplicateInFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp nhập khẩu không đúng mẫu.
        /// </summary>
        public static string Error_ImportFile_NotMatchTemplate {
            get {
                return ResourceManager.GetString("Error_ImportFile_NotMatchTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp nhậu khẩu không đúng mẫu, vui lòng kiểm tra lại vị trí dòng bắt đầu nhập khẩu.
        /// </summary>
        public static string Error_ImportFileColumnHeaderPossitionInvalid {
            get {
                return ResourceManager.GetString("Error_ImportFileColumnHeaderPossitionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp nhập khẩu không đúng mẫu, vị trí cột [{0}] tại worksheet [{1}] - [{2}] sai hoặc không tồn tại trong file mẫu.
        /// </summary>
        public static string Error_ImportFileColumnPossitionInvalid {
            get {
                return ResourceManager.GetString("Error_ImportFileColumnPossitionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin {0} không đúng định dạng, định dạng đúng là [tháng/năm].
        /// </summary>
        public static string Error_ImportFileDateFormatInvalidMMYYYY {
            get {
                return ResourceManager.GetString("Error_ImportFileDateFormatInvalidMMYYYY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp nhập khẩu không đúng định dạng. Vui lòng kiểm tra lại.
        /// </summary>
        public static string Error_ImportFileFormat {
            get {
                return ResourceManager.GetString("Error_ImportFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tệp nhập khẩu không đúng mẫu, số lượng cột tại worksheet [{1}] trong file mẫu là {0}.
        /// </summary>
        public static string Error_ImportFileWorksheetPossitionInvalid {
            get {
                return ResourceManager.GetString("Error_ImportFileWorksheetPossitionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ MISA để được trợ giúp.
        /// </summary>
        public static string ErrorException {
            get {
                return ResourceManager.GetString("ErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ.
        /// </summary>
        public static string ErrorValidate_NotValid {
            get {
                return ResourceManager.GetString("ErrorValidate_NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} không được phép để trống.
        /// </summary>
        public static string ErroValidate_Required {
            get {
                return ResourceManager.GetString("ErroValidate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Không được phép để trống.
        /// </summary>
        public static string ErroValidate_Required1 {
            get {
                return ResourceManager.GetString("ErroValidate_Required1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đọc dữ liệu nhập khẩu thành công.
        /// </summary>
        public static string Msg_ImportFileReadSuccess {
            get {
                return ResourceManager.GetString("Msg_ImportFileReadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập khẩu thành công.
        /// </summary>
        public static string Msg_ImportSuccess {
            get {
                return ResourceManager.GetString("Msg_ImportSuccess", resourceCulture);
            }
        }
    }
}
